# Generated by Django 5.2 on 2026-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chart_image", models.ImageField(upload_to="charts/%Y/%m/%d/")),
                ("ai_result", models.JSONField(blank=True, null=True)),
                ("signal", models.CharField(blank=True, max_length=10)),
                ("confidence", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
