# Generated by Django 5.2 on 2026-01-09 12:56

import django.db.models.deletion
import market_scanner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_scanner", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisrecord",
            name="confidence",
        ),
        migrations.AddField(
            model_name="analysisrecord",
            name="json_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=market_scanner.models.AnalysisRecord.user_directory_path,
            ),
        ),
        migrations.AddField(
            model_name="analysisrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="analysisrecord",
            name="chart_image",
            field=models.ImageField(
                upload_to=market_scanner.models.AnalysisRecord.user_directory_path
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "security_question",
                    models.CharField(help_text="密保问题：你的宠物叫什么？", max_length=100),
                ),
                ("security_answer", models.CharField(max_length=100)),
                ("api_key", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "api_base_url",
                    models.CharField(
                        default="https://dashscope.aliyuncs.com/compatible-mode/v1",
                        max_length=200,
                    ),
                ),
                (
                    "selected_model",
                    models.CharField(default="qwen-vl-max", max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
