# Generated by Django 5.2 on 2026-01-10 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_scanner", "0002_remove_analysisrecord_confidence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrecord",
            name="final_signal",
            field=models.CharField(blank=True, max_length=10, verbose_name="策略最终信号"),
        ),
        migrations.AddField(
            model_name="analysisrecord",
            name="raw_signal",
            field=models.CharField(blank=True, max_length=10, verbose_name="AI原始信号"),
        ),
        migrations.AddField(
            model_name="analysisrecord",
            name="strategy_reason",
            field=models.CharField(blank=True, max_length=200, verbose_name="策略判定理由"),
        ),
        migrations.CreateModel(
            name="StrategyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_score_buy",
                    models.IntegerField(default=75, verbose_name="买入最低评分"),
                ),
                (
                    "require_bullish_ma",
                    models.BooleanField(default=True, verbose_name="必须均线多头"),
                ),
                (
                    "max_risk_factors",
                    models.IntegerField(default=1, verbose_name="允许最大风险因子数"),
                ),
                (
                    "allow_sideways",
                    models.BooleanField(default=False, verbose_name="允许震荡趋势"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
