# Generated by Django 5.2 on 2026-01-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_scanner", "0003_analysisrecord_final_signal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyconfig",
            name="allow_high_volatility",
            field=models.BooleanField(default=False, verbose_name="允许高波动率"),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="min_confidence",
            field=models.IntegerField(default=60, verbose_name="最低AI置信度"),
        ),
    ]
