# Generated by Django 5.2 on 2026-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_scanner", "0005_paperorder_virtualaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualaccount",
            name="broker_app_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="GTJA AppID"
            ),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="broker_app_secret",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="GTJA AppSecret"
            ),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="broker_customer_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="资金账号"
            ),
        ),
    ]
